# Jekyll configuration

name: "An Introduction to C# graphics"
description: Various coding examples in C# and libraries for the budding Graphics programmer

# Url is currently only used only for the RSS feed in feed.xml
url: https://nuclearfossil.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: nuclearfossil
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: nuclearfossil
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  syntax_highlighter: rouge
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
